services:
  - type: web
    name: crm-prospector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SHEETS_URL
        value: https://script.google.com/macros/s/AKfycbwangi6yd__KZLF74gapavnHB6pYT-At5h1qzwJE5OGdYhBp_GzjdaLm6dQD0997xLErg/exec
      - key: ZONA
        value: El Raal, Murcia, Spain
      - key: RADIO_METROS
        value: "10000"
